import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import ContextProvider from "./_custom-hooks/ContextProvider";
import "./globals.css";
const inter = Poppins({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}  antialiased`}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
